<p>Las excepciones son situaciones anómalas provocadas en tiempo de ejecución que interrumpen de forma abrupta la ejecución.</p>

<p>En el siguiente ejemplo se intenta hacer una división entre cero y se provoca la excepción.</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/1/<lenguaje>/1.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/1/<lenguaje>/1.txt"></pre>
</div>

<p>En este otro ejemplo:</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/1/<lenguaje>/2.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/1/<lenguaje>/2.txt"></pre>
</div>

<p>se llama al método <code>suma</code> con un único argumento en lugar de los dos que espera el método y ello produce una excepción que interrumpe la ejecución.</p>
